{{- if not .Values.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: infokala
  labels:
    {{- include "infokala.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.secret.secretKey | b64enc }}
  KOMPASSI_OAUTH2_CLIENT_ID: {{ .Values.secret.kompassiClientId | b64enc }}
  KOMPASSI_OAUTH2_CLIENT_SECRET: {{ .Values.secret.kompassiClientSecret | b64enc }}
  DATABASE_URL: {{ .Values.secret.databaseUrl | b64enc }}
{{- end }}
