apiVersion: v1
kind: Service
metadata:
  name: gunicorn
  labels:
    {{- include "infokala.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    {{- include "infokala.selectorLabels" . | nindent 4 }}
